Testing this

diff --git a/.github/workflows/ci_build.yml b/.github/workflows/ci_build.yml
--- a/.github/workflows/ci_build.yml
+++ b/.github/workflows/ci_build.yml
@@ -21,13 +21,22 @@ jobs:
     - name: "Test SDK versions"
       run: |
         xcodebuild -showsdks
-    - name: Build with xcodebuild
-      run: |
-        xcodebuild -project ./Mlem.xcodeproj -scheme "Mlem" -sdk "iphonesimulator16.2" -quiet -resultBundlePath "build_results.xcresult"
-    - uses: kishikawakatsumi/xcresulttool@v1
+
+    - name: "Xcode Test"
+      uses: sersoft-gmbh/xcodebuild-action@v2
       with:
-        path: build_results.xcresult
-        upload-bundles: never # Permission issues with uploading
-      if: success() || failure()
+        project: Mlem.xcodeproj
+        scheme: Mlem
+        destination: platform=Simulator,name=iPhone 14,OS=16.4'
+        action: test
+
+    #- name: Build with xcodebuild
+    #  run: |
+    #    xcodebuild -project ./Mlem.xcodeproj -scheme "Mlem" -sdk "iphonesimulator16.2" -quiet -resultBundlePath "build_results.xcresult"
+    #- uses: kishikawakatsumi/xcresulttool@v1
+    #  with:
+    #    path: build_results.xcresult
+    #    upload-bundles: never # Permission issues with uploading
+    #  if: success() || failure()
       # ^ This is important because the action will be run
       # even if the test fails in the previous step.
